# Welcome to your Jekyll configuration.

# Site Settings
locale: "en-US"
title: "Farida Hanna Campbell - Academic Portfolio"
title_separator: "|"
name: "Farida Hanna Campbell"
description: "Exploring the intersection of computational biology, bioinformatics, and big data analytics."
url: "https://academicpages.github.io"
baseurl: ""
repository: "Cartesian1671/rbnsnlb.github.io"

# SEO Related
google_site_verification: ""
bing_site_verification: ""
alexa_site_verification: ""
yandex_site_verification: ""

# Social Sharing
twitter:
  username: "https://www.twitter.com/DBBiopharm" # Replace with your actual Twitter handle
linkedin:
  username: "https://www.linkedIn.com/FaridaHannCampbell" # Replace with your actual Twitter handle

facebook: "https://www.facebook.com/DBBiopharmaceuticals"
  username: "DBBiopharmaceuticals"
  app_id: ""
  publisher: ""
og_image: "https://github.com/Cartesian1671/rbnsnlb.github.io/blob/master/images/20211120_173223.jpg" # Use a professional headshot or related image

# Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id: "" # Your Google Analytics tracking ID

# Site Author
author:
  name: "Farida Hanna Campbell"
  avatar: "20211120_173223.jpg" # Ensure this image is in your '/images/' directory
  bio: "Biography: A brief overview of your professional interests, achievements, and goals."
  location: "Maastricht, NL"
  employer: "7 Provincien"
  researchgate: "https://www.researchgate.net/profile/Fh-Campbell-2"
  email: "fhcampbell@7Provincien.com"
  linkedin: "https://www.linkedin.com/in/faridahanncampbell/"
  orcid: "http://orcid.org/0000-0002-0546-6200"
  twitter: "DBBiopharmaceuticals" # Replace with your actual Twitter handle
  twitch: "https://twitch.com/g4zorg"

# Collections
collections:
  teaching:
    output: false
    permalink: "/teaching/:path/"
  publications:
    output: true
    permalink: "/publications/:path/"
  portfolio:
    output: true
    permalink: "/portfolio/:path/"
  talks:
    output: false
    permalink: "/talks/:path/"

# Markdown Processing
kramdown:
  input: GFM

# Plugins (Ensure these are supported by your hosting environment)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
